### ISSUE TITLE
[Question] Redis, when is needed? and how updates work?

### ISSUE THREAD

**Issue by lordraiden** [maxlerebourg/crowdsec-bouncer-traefik-plugin#102]
Is redis a recommendation in any case due to the size of the block lists, or only in scenarios with websites with a lot of traffic?
____

How I can get automatic updates of the bouncer? if I remove the line with the version it will download always the latest version?

experimental:
  plugins:
    crowdsec-bouncer-traefik-plugin:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      **version: "v1.1.12"**

**Comment by mathieuHa** [comment]
Hey @lordraiden,

_Is redis a recommendation in any case due to the size of the block lists, or only in scenarios with websites with a lot of traffic?_

Well, I have seen blocklist range from a few thousand to several tens of thousands.  It depends on the activity on your website and the period of time you keep a decision active, but also on the blocklist you may subscribe in the crowdsec console. 

It either get stored in memory or in redis.

I have no benchmark showing better performance for either choice, but I like to separate tasks and Traefik does its proxy things and Redis stores the data for the plugin.

_How I can get automatic updates of the bouncer? if I remove the line with the version it will download always the latest version?_

It won't work as Traefik download only specifics release from github when started, there is no latest implemented in Traefik like we can do with containers.

However, this shouldn't be a problem, we have reached some stability in the plugin and will update when we have time for improvement requested or some documentation update. 
Also we follow Traefik and Crowdsec release to ensure we stay compatible.

Hope it anwsers your question

**Comment by mathieuHa** [comment]
Closing since the question has been answered.
