### ISSUE TITLE
[FEATURE] Mark bounced requests in access.log

### ISSUE THREAD

**Issue by dawidkulpa** [maxlerebourg/crowdsec-bouncer-traefik-plugin#186]
**Is your feature request related to a problem? Please describe.** 🐛
Currently, when a request is bounced, the only way to see that in access.log is by looking for "403" codes, but as you can imagine, this could also mean that the underlying app returned 403.

**Describe the solution you'd like** ✨
Add a request header clearly stating if the request was blocked by crowdsec.

**Comment by maxlerebourg** [comment]
Hey, it's an excellent idea, let's do it.
What do want to expose ? The request decision (Header `CS-Decision: ban` (or `captcha`)) or just the fact that the bouncer has block this request (Header `CS-Decision: 1`)

**Comment by mathieuHa** [comment]
Yeah, like max said, we could add it in the plugin, but I think by default it should be disabled.  
Adding information in the response can give an attacker information that the product Crowdsec has blocked the request. So it should be activated by the admin knowingly.  

We're open to PR if you wan't try to add it, otherwise we will try to do it when we get some free time to work on it
