### ISSUE TITLE
Significant slow down after updating to v1.1.1 and configuring to use redis

### ISSUE THREAD

**Issue by aleksandarmomic** [maxlerebourg/crowdsec-bouncer-traefik-plugin#30]
My setup:
- 14 services using the bouncer
- Local redis cache in the same docker network as traefik

Right after upgrading to v1.1.1 every request is very slow (45+ seconds). Services are unusable in that state. 
I have verified the redis cache and IPs successfully get cached in it with a `"f"` value, so the connection is working, but something is wrong and I could not figure out what it is. 

When I revert to v1.1.0 everything goes back to normal.
With `redisCacheEnabled: false` on version v1.1.1, the issue doesn't appear.

It's definitely something to do when redis gets involved.

**Comment by maxlerebourg** [comment]
Re Aleksandarmonic, thanks a lot to beta-test our new feature 😉
If you look at the code, I rewrite a package to communicate with Redis so it can be unstable. We did this because all the other client library were not supported by Traefik.

I need to have more information about your setup, my local setup works (the same as in the exemple folder)

Can you test it too on your setup ? (maybe that need some modifications)

**Comment by maxlerebourg** [comment]
I have worked on solution but I don't think this one could handle a lot of simultaneous connection, don't hesitate to tell me, if the provided solution fits your needs 👍

**Comment by aleksandarmomic** [comment]
Hi, thank you for the quick fix! I didn't get a chance to try it out as I don't have access to my server right now. I will try it out in a day or two and let you know if the issue is fixed.

**Comment by aleksandarmomic** [comment]
@maxlerebourg Running on 1.1.2 right now with redis enabled. I haven't observed any slow-downs yet, but I will continue monitoring. So far so good! 😊

**Comment by maxlerebourg** [comment]
Yes, that's awesome ! Will close this issue, tell us if you need more features !
Thanks a lot 😄
