### ISSUE TITLE
Cache is disabled but tested ips remaining banned due to cache hits?

### ISSUE THREAD

**Issue by mannp** [maxlerebourg/crowdsec-bouncer-traefik-plugin#42]
Hi there

I have got your plugin working now with kubernetes but noticed an odd occurrence 

Cache is currently disabled;

`redisCacheEnabled: false`

But manually added ips remain banned due to cache hits?

`cache:hit isBanned:true`

How can that be with cache disabled?

Also, is  crowdsecMode set to none when redis is disabled?

Thanks :)

**Comment by maxlerebourg** [comment]
The README says:

- RedisCacheEnabled
  - bool
  - default: false
  - enable redis cache instead of filesystem cache
 
I think your setup uses the local cache. 
To really disable the cache, you need to set the mode to `none`

![image](https://user-images.githubusercontent.com/22881669/203857559-2eaa3bd2-8c58-49de-a52e-785e050c4c6b.png)

I hope I've helped you, don't hesitate to put a star, it's appreciated 😃

**Comment by maxlerebourg** [comment]
Can I close the issue ?

**Comment by mannp** [comment]
I noted in my initial post that about crowdsecMode = none.

The main point (which I failed to mention) was that I left it for 10 mins and the local cache never reset after unbanning the ip.

**Comment by maxlerebourg** [comment]
If you are in `live` mode, the local cache as the redis cache use the duration ban sent by crowdsec. If you want a unban after a period, use `none` or `stream` mode. 😄
